name: Naukri Automation

on:
  schedule:
    - cron: '0 * * * *'  # run every hour
  workflow_dispatch:     # allows manual trigger

jobs:
  run_naukri:
    runs-on: ubuntu-latest
    env:
      NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Run Naukri Automation
        run: python NaukriAutomation.py

      - name: Upload log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: automation-log
          path: automation.log
